package mia.core.model;

import java.util.Date;

public class MiaUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.ID
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.USER_LOGIN
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private String userLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.FIRST_NAME
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.LAST_NAME
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.PASSWORD
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.BIRTH_DAY
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private Date birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.PHONE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.EMAIL
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.SESSION_ID
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.USER_STATUS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.IS_ENABLE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private Integer isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MIA_USERS.REGISTER_DATE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    private Date registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.ID
     *
     * @return the value of MIA_USERS.ID
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.ID
     *
     * @param id the value for MIA_USERS.ID
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.USER_LOGIN
     *
     * @return the value of MIA_USERS.USER_LOGIN
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public String getUserLogin() {
        return userLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.USER_LOGIN
     *
     * @param userLogin the value for MIA_USERS.USER_LOGIN
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.FIRST_NAME
     *
     * @return the value of MIA_USERS.FIRST_NAME
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.FIRST_NAME
     *
     * @param firstName the value for MIA_USERS.FIRST_NAME
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.LAST_NAME
     *
     * @return the value of MIA_USERS.LAST_NAME
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.LAST_NAME
     *
     * @param lastName the value for MIA_USERS.LAST_NAME
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.PASSWORD
     *
     * @return the value of MIA_USERS.PASSWORD
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.PASSWORD
     *
     * @param password the value for MIA_USERS.PASSWORD
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.BIRTH_DAY
     *
     * @return the value of MIA_USERS.BIRTH_DAY
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.BIRTH_DAY
     *
     * @param birthDay the value for MIA_USERS.BIRTH_DAY
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.PHONE
     *
     * @return the value of MIA_USERS.PHONE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.PHONE
     *
     * @param phone the value for MIA_USERS.PHONE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.EMAIL
     *
     * @return the value of MIA_USERS.EMAIL
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.EMAIL
     *
     * @param email the value for MIA_USERS.EMAIL
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.SESSION_ID
     *
     * @return the value of MIA_USERS.SESSION_ID
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.SESSION_ID
     *
     * @param sessionId the value for MIA_USERS.SESSION_ID
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.USER_STATUS
     *
     * @return the value of MIA_USERS.USER_STATUS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.USER_STATUS
     *
     * @param userStatus the value for MIA_USERS.USER_STATUS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.IS_ENABLE
     *
     * @return the value of MIA_USERS.IS_ENABLE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.IS_ENABLE
     *
     * @param isEnable the value for MIA_USERS.IS_ENABLE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MIA_USERS.REGISTER_DATE
     *
     * @return the value of MIA_USERS.REGISTER_DATE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MIA_USERS.REGISTER_DATE
     *
     * @param registerDate the value for MIA_USERS.REGISTER_DATE
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
}