package mia.core.dao;

import mia.core.model.MiaUser;

public interface MiaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIA_USERS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIA_USERS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    int insert(MiaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIA_USERS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    int insertSelective(MiaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIA_USERS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    MiaUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIA_USERS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    int updateByPrimaryKeySelective(MiaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MIA_USERS
     *
     * @mbggenerated Tue May 21 01:04:34 ICT 2013
     */
    int updateByPrimaryKey(MiaUser record);

	MiaUser getUserByUserLogin(String username);
}